### get posts
GET http://localhost:3003/api/blogs

### create post

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "ALX Software Engineering",
    "author": "ALX Bootcamp",
    "url": "https://learn-react-fromzero.com/blogs/express",
    "likes": 91862
}

### create user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Sami1",
    "name": "Samuel Teklay",
    "password": "GemeTK@123"
}

### get users
GET http://localhost:3003/api/users